apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # atau NodePort jika tidak pakai cloud provider
